version: '3.8'

services:
  mysql:
    image: mysql:8
    container_name: mysql8
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: passwd
      MYSQL_DATABASE: dbOtus
      MYSQL_USER: studentOtus
      MYSQL_PASSWORD: passwdOtus
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./my.cnf:/etc/mysql/conf.d/my.cnf

volumes:
  mysql_data:
    driver: local